require("lazy-plugins")
require("gral-configs")
require("gral-keymaps")
require("colorschemes")
require("toggleterm-config")
require("telescope-config")
require("treesitter-config")
require("refactor-config")
require("lf-config")
require("snippets")

require("lsp")
require("debuger")
